#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width        0
bspc config window_gap          10
bspc config border_radius 		10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a copyq state=floating

# get auth work with polkit-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Setup Displays
autorandr -c &

# Start Blueberry Tray
blueberry-tray &

# Starting Compositor
picom --config $HOME/.config/picom/picom.conf --experimental-backends &

# Start Network Manager Applet
nm-applet &

# Start desktop notifications
dbus-launch dunst --config ~/.config/dunst/dunstrc &

# Setup Trackpad for Minecraft, Enable Trackpad While Typing
xinput --set-prop bcm5974 "libinput Disable While Typing Enabled" 0 &

# Set Trackpad to Horizontal Scrolling
# xinput --set-prop bcm5974 "libinput Scroll Method Enabled" 0, 1, 0 &

# rclone
rclone mount googledrive: ~/google-drive &

# polybar
polybar &

# discord-canary
discord-canary --start-minimized &

# mailspring
mailspring -b &

# flameshot
flameshot &

# copyq
copyq &

# ulauncher
ulauncher --hide-window --no-window-shadow &

# microsoft todo desktop (kuro)
kuro &

# battery notifications
batsignal -I "/usr/share/icons/Papirus-Dark/16x16@2x/devices/battery.svg" &

# set wallpaper
nitrogen --restore &

# alacritty dpi setting
export WINIT_HIDPI_FACTOR=1.0 alacritty &
